language: R
sudo: false
cache: packages
notifications:
  email:
    on_success: change
    on_failure: change
after_success:
- Rscript -e "devtools::install()"
- Rscript -e "travisDrat::deploy_drat('HBGDki/drat')"
env:
  global:
    secure: CP1fMCeumfL1Of7u7L2Y6s/WSyvpGHNCYX2vIvImfDorUaJgwyYDua3PlslhPnq8txDP98vArTPYcC2ie3kT3Kp9kzjyxtE8CNTtQbSZqAXnDkF7dp8PxdVQkR8dJdCANGFTJQGkWnddsjLuiaHRr1WqA3HUBHzxqN3eMR5FSuZ0VHqm0VUUfaNPWlzNQ/oaPMW6g2F9ojrsprc1+azvIy5/3a4DmahBgqcP6j0VgpyGWKTN+a8exRZKxbNKiKrgzWazpwb0x2a6JgpF+LMRKGpQ9GldyJoAzhzgAILYa70ulkQXyO8mUt1EjK/TA2L00prrd10os8s4TwYE7uesucmGEecOXVULn+96DaYPTL+JIZgROXgBNw6C8ptS6fo0peQw6y8in+OWGZdBGhwp5041hwSUS/zi760g1QnTjewRFspAvuN9ED40C8mgWsUeZmTUuczMV3Tuxmn6/VS97jnvjgpWGLojLm4D7VOZxHnjG+oCNIrGD2keFr2qGryDffmmpVk4Wexv8WkoHDpNOodLfvlAO9qLXf7KFTKUAB4eAfJDV2s3d4v/pMO3Ibfa9y8BhufwRu22B09mnByRr/4Oi0FcfrEbQ7MLGt9e84ndqJK7eA1Q8tQSmgXrmwcYPXhk891qJXyxBM1EkwwfApmMkWqIbtpADClUnyzNNlM=
